name: betterFishing
version: '2.0.0'
main: jefry.plugin.betterFishing.BetterFishing
api-version: '1.21'
depend: [Vault]
softdepend: [Essentials]

commands:
  betterfishing: # Main command
    description: Main command for the BetterFishing plugin.
    usage: /betterfishing <subcommand> [args...]
    aliases: [bf, bfish, fishrod]
    permission: betterfishing.use

permissions:
  betterfishing.use:
    description: Base permission for BetterFishing commands.
    default: op
  betterfishing.reload:
    description: Allows reloading BetterFishing configurations.
    default: op
  betterfishing.give:
    description: Allows giving custom fishing rods.
    default: op
  betterfishing.reset: # General reset permission
    description: Allows resetting plugin data like scoreboards.
    default: op
  # Admin Panel Permissions
  betterfishing.admin:
    description: Access to the main admin panel via GUI.
    default: op
  betterfishing.admin.rods:
    description: Allows managing fishing rod configurations (GUI/commands).
    default: op
  betterfishing.admin.fish:
    description: Allows managing fish item configurations (GUI/commands).
    default: op
  # Backpack System Permissions
  betterfishing.backpack.use:
    description: Allows players to open and use the backpack upgrade GUI.
    default: true
  betterfishing.admin.backpack:
    description: Allows admins to manage player backpack slots via commands.
    default: op